### ISSUE TITLE
Renderer not found

### ISSUE THREAD

**Issue by benjijamorris** [matanat/dae_counterfactual#1]
First of all, thanks for the awesome work! I've successfully trained the `retina128_autoenc_130M` model on my own data with some small modifications to get things running. I'm now trying to explore the model via the `manipulate_retina` notebook, but am running into issues with the `model.render()` method. It seems like the `render_condition` and `render_uncondition` methods are not included in the repo (I think they should be included in the `from renderer import *`, but the `renderer.py` file is not included). 

I might be missing something, but I can't seem to find these files. Thanks again!

**Comment by matanat** [comment]
Hi @benjijamorris,

Happy to hear you find our work useful. 
You're absolutely right, my bad. I just pushed that file to the repo. 
Cheers!

**Comment by benjijamorris** [comment]
Fantastic! Everything is working now, thanks for the help.
